# Generated by Django 3.2.12 on 2022-03-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            SELECT * FROM iasql_install(
                'aws_vpc@0.0.1',
                'aws_security_group@0.0.1',
                'aws_elb@0.0.1',
                'aws_cloudwatch@0.0.1',
                'aws_ecr@0.0.1',
                'aws_ecs_fargate@0.0.1',
                'aws_rds@0.0.1'
            );
            """,
            """
            SELECT * FROM iasql_uninstall(
                'aws_vpc@0.0.1',
                'aws_security_group@0.0.1',
                'aws_elb@0.0.1',
                'aws_cloudwatch@0.0.1',
                'aws_ecr@0.0.1',
                'aws_ecs_fargate@0.0.1',
                'aws_rds@0.0.1'
            );
            """
        )
    ]
